#环境变量
variables:
  #发版dev测试环境
  K8S_ENVIRONMENT: dev
  #发版应用
  APPLICATION: hello-world
  #镜像仓库用户
  CONTAINER_REPO_USERNAME: ${HARBOR_REPO_USERNAME}
  #镜像仓库密码
  CONTAINER_REPO_PASSWORD: ${HARBOR_REPO_PASSWORD}
  #mvn_deploy,mvn_install,gradle编译工具
  BUILD_TOOL: gradle

#运行前设置获取变量
before_script:
  - export APP_TAG="${CI_COMMIT_TAG}"
  - if [ "$CI_COMMIT_TAG" == null ];then export CI_COMMIT_TAG="${CI_COMMIT_REF_NAME}";fi
#gradle编译
build_image_gradle:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH  ==  "master" && $BUILD_TOOL == "gradle" '
  tags:
    - jks
  script:
    - echo ${APPLICATION}
    - echo ${APP_TAG}
    - gradle jib  

#推送nexus的jar包
build_image_mvn_deploy:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH  ==  "master" && $BUILD_TOOL == "mvn_deploy"'
  tags:
    - jks
  script:
    - echo ${APPLICATION}
    - mvn -B -q -gs $HOME/settings.xml clean deploy

#mvn编译
build_image_mvn_deploy:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH  ==  "master" && $BUILD_TOOL == "mvn_deploy"'
  tags:
    - jks
  script:
    - echo ${APPLICATION}
    - mvn -B -q -gs $HOME/settings.xml clean deploy

#阿里云打包gradle编译
build_aliyun_image_gradle:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG !~ "/^$/" && $BUILD_TOOL == "gradle" '
  variables:
    CONTAINER_REPO_USERNAME: hi31813309@aliyun.com
    CONTAINER_REPO_PASSWORD: xiaofan@1
  tags:
    - jks
  script:
    - echo ${APPLICATION}
    - echo ${CI_COMMIT_TAG}
    - echo ${CI_COMMIT_REF_NAME}
    - gradle --stacktrace jib -Ppro
