#环境变量
variables:
  #发版dev测试环境
  K8S_ENVIRONMENT: dev
  #发版应用
  APPLICATION: hello-world
  #容器仓库用户密码
  CONTAINER_REPO_USERNAME: ${HARBOR_REPO_USERNAME}
  CONTAINER_REPO_PASSWORD: ${HARBOR_REPO_PASSWORD}
  #CONTAINER_REPO_USERNAME: (if [ "${CI_COMMIT_TAG}" == "" ]; then "${ALIYUN_REPO_USERNAME}}";else ${HARBOR_REPO_USERNAME};fi);
  #CONTAINER_REPO_PASSWORD: (if [ "${CI_COMMIT_TAG}" == "" ]; then "${ALIYUN_REPO_USERNAME}}";else ${HARBOR_REPO_PASSWORD};fi);
  #阿里云仓库
  ALIYUN_REPO_USERNAME: ${ALIYUN_REPO_USERNAME}
  ALIYUN_REPO_PASSWORD: ${ALIYUN_REPO_PASSWORD}
  #mvn_deploy,mvn_install,gradle编译工具
  BUILD_TOOL: gradle
build_aliyun_image_gradle:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG !~ "/^$/" && $BUILD_TOOL == "gradle" '
  variables:
    CONTAINER_REPO_USERNAME: hi31813309@aliyun.com
    CONTAINER_REPO_PASSWORD: xiaofan@1
  tags:
    - jks
  script:
    - echo ${APPLICATION}
    - echo ${CI_COMMIT_TAG}
    - echo ${CI_COMMIT_REF_NAME}
    - gradle --stacktrace jib -Ppro